services:
  astroweather_frontend:
    build:
      context: .
      args:
        - API_URL=http://host.docker.internal:6723
    image: astroweather_frontend
    container_name: astroweather_frontend
    ports:
      - "3020:3000"
    environment:
      - API_URL=http://astroweather_backend:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - astroweather_network

networks:
  astroweather_network:
    external: true
