services:
  astroweather_frontend:
    build:
      context: .
      args:
        - API_URL=http://localhost:6723
    image: astroweather_frontend
    container_name: astroweather_frontend
    ports:
      - "3020:3000"
    environment:
      - API_URL=http://localhost:6723
    network_mode: host
    restart: unless-stopped
