services:
  astroweather_frontend:
    build: .
    image: astroweather_frontend
    container_name: astroweather_frontend
    ports:
      - "3020:3000"
    environment:
      - API_URL=http://astroweather_backend:8000
    restart: unless-stopped
    networks:
      - astroweather_network
      - proxy

networks:
  astroweather_network:
    external: true
  proxy:
    external: false
    name: proxy
